# Generated by Django 5.1.4 on 2025-02-07 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('especialidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.TextField()),
                ('responsable', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En remodelación', 'En remodelación'), ('Ocupada', 'Ocupada')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reforma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('reforma', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Finalizado', 'Finalizado')], max_length=50)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oficinas.contratista')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oficinas.oficina')),
            ],
        ),
        migrations.CreateModel(
            name='ReformaSuministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.IntegerField()),
                ('reforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oficinas.reforma')),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Oficinas.suministro')),
            ],
        ),
    ]
