# Generated by Django 5.1.4 on 2025-02-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oficinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='fotografia',
            field=models.FileField(blank=True, null=True, upload_to='contratista'),
        ),
        migrations.AddField(
            model_name='suministro',
            name='fotografia',
            field=models.FileField(blank=True, null=True, upload_to='suministro'),
        ),
    ]
