# Generated by Django 5.1.4 on 2025-02-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oficinas', '0002_contratista_fotografia_suministro_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratista',
            name='fotografia',
            field=models.FileField(blank=True, null=True, upload_to='contrato'),
        ),
        migrations.AlterField(
            model_name='suministro',
            name='fotografia',
            field=models.FileField(blank=True, null=True, upload_to='sumini'),
        ),
    ]
