# Generated by Django 5.1.4 on 2025-02-08 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oficinas', '0003_alter_contratista_fotografia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suministro',
            old_name='fotografia',
            new_name='evidencias',
        ),
    ]
